
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_ids.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_IDS_H
#define __STAI_ATON_IDS_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_IDS_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_IDS_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_ids_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_ids_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_ids_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_ids_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_ids_get_context_size(void)
{
  return STAI_IDS_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_ids_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_ids_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_ids_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_ids_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_ids_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_ids_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_ids_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_ids_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_ids_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_ids_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_ids_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_ids_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_ids_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_ids_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_ids_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_ids_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_ids_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_ids_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_ids_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_ids_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_ids_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_ids_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_ids_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_ids_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_ids_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_ids_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_ids_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_ids_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_ids_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_ids_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_ids_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_ids_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_ids_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_ids_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_ids_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_ids_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_ids_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_IDS_STATES_NUM  (0)
#define STAI_IDS_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_IDS_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_IDS_IN_NUM (1)
#define STAI_IDS_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_IDS_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_IDS_IN_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_IDS_IN_SIZES \
  { \
    11 \
  }
#define STAI_IDS_IN_SIZES_BYTES \
  { \
    11 \
  }

#define STAI_IDS_IN_1_ALIGNMENT (32)
#define STAI_IDS_IN_1_NAME "Input_0_out_0"
#define STAI_IDS_IN_1_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_IDS_IN_1_FORMAT (STAI_FORMAT_S8)
#define STAI_IDS_IN_1_SIZE (11)
#define STAI_IDS_IN_1_SIZE_BYTES (11)
#define STAI_IDS_IN_1_CHANNEL (1)
#define STAI_IDS_IN_1_HEIGHT (1)
#define STAI_IDS_IN_1_WIDTH (11)
#define STAI_IDS_IN_1_RANK (2)
#define STAI_IDS_IN_1_SHAPE \
  { \
    1, 11 \
  }
#define STAI_IDS_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_IDS_IN_1_SCALES \
  { \
    0.024639930576086 \
  }
#define STAI_IDS_IN_1_OFFSETS \
  { \
    4 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_IDS_OUT_NUM (1)
#define STAI_IDS_OUT_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_IDS_OUT_NAMES \
  { \
    "Quantize_14_out_0" \
  }
#define STAI_IDS_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_IDS_OUT_SIZES \
  { \
    5 \
  }
#define STAI_IDS_OUT_SIZES_BYTES \
  { \
    5 \
  }

#define STAI_IDS_OUT_1_ALIGNMENT (32)
#define STAI_IDS_OUT_1_NAME "Quantize_14_out_0"
#define STAI_IDS_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_IDS_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_IDS_OUT_1_SIZE (5)
#define STAI_IDS_OUT_1_SIZE_BYTES (5)
#define STAI_IDS_OUT_1_CHANNEL (1)
#define STAI_IDS_OUT_1_HEIGHT (1)
#define STAI_IDS_OUT_1_WIDTH (5)
#define STAI_IDS_OUT_1_RANK (2)
#define STAI_IDS_OUT_1_SHAPE \
  { \
    1, 5 \
  }
#define STAI_IDS_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_IDS_OUT_1_SCALES \
  { \
    0.00124665896873921 \
  }
#define STAI_IDS_OUT_1_OFFSETS \
  { \
    36 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_IDS_WEIGHTS_NUM (11)
#define STAI_IDS_WEIGHTS_ALIGNMENTS \
  { \
    32, 32, 16, 32, 32, 16, 32, 32, 16, 16, 16 \
  }
#define STAI_IDS_WEIGHTS_NAMES \
  { \
    "Gemm_4_weights_transposed_3", "Gemm_7_weights_transposed_9", "Gemm_10_weights_transposed_15", "Gemm_13_weights_transposed_21", "Gemm_4_conv_4_off_bias_32", "Gemm_7_conv_10_zero_off_35", "Gemm_7_conv_10_off_bias_41", "Gemm_10_conv_16_zero_off_44", "Gemm_10_conv_16_off_bias_50", "Gemm_13_conv_22_zero_off_53", "Gemm_13_conv_22_off_bias_59" \
  }
#define STAI_IDS_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32 \
  }
#define STAI_IDS_WEIGHTS_SIZES \
  { \
    704, 4096, 2048, 160, 64, 1, 64, 1, 32, 1, 5 \
  }
#define STAI_IDS_WEIGHTS_SIZES_BYTES \
  { \
    704, 4096, 2048, 160, 256, 1, 256, 1, 128, 1, 20 \
  }

#define STAI_IDS_WEIGHTS_1_ALIGNMENT (32)
#define STAI_IDS_WEIGHTS_1_NAME "Gemm_4_weights_transposed_3"
#define STAI_IDS_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_IDS_WEIGHTS_1_FORMAT (STAI_FORMAT_S8)
#define STAI_IDS_WEIGHTS_1_SIZE (704)
#define STAI_IDS_WEIGHTS_1_SIZE_BYTES (704)
#define STAI_IDS_WEIGHTS_1_CHANNEL (11)
#define STAI_IDS_WEIGHTS_1_HEIGHT (1)
#define STAI_IDS_WEIGHTS_1_WIDTH (1)
#define STAI_IDS_WEIGHTS_1_BATCH (11)
#define STAI_IDS_WEIGHTS_1_RANK (4)
#define STAI_IDS_WEIGHTS_1_SHAPE \
  { \
    64, 1, 1, 11 \
  }
#define STAI_IDS_WEIGHTS_1_SCALE_OFFSET_NUM (1)
#define STAI_IDS_WEIGHTS_1_SCALES \
  { \
    0.00237142923288047 \
  }
#define STAI_IDS_WEIGHTS_1_OFFSETS \
  { \
    0 \
  }

#define STAI_IDS_WEIGHTS_2_ALIGNMENT (32)
#define STAI_IDS_WEIGHTS_2_NAME "Gemm_7_weights_transposed_9"
#define STAI_IDS_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_IDS_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_IDS_WEIGHTS_2_SIZE (4096)
#define STAI_IDS_WEIGHTS_2_SIZE_BYTES (4096)
#define STAI_IDS_WEIGHTS_2_CHANNEL (64)
#define STAI_IDS_WEIGHTS_2_HEIGHT (1)
#define STAI_IDS_WEIGHTS_2_WIDTH (1)
#define STAI_IDS_WEIGHTS_2_BATCH (64)
#define STAI_IDS_WEIGHTS_2_RANK (4)
#define STAI_IDS_WEIGHTS_2_SHAPE \
  { \
    64, 1, 1, 64 \
  }
#define STAI_IDS_WEIGHTS_2_SCALE_OFFSET_NUM (1)
#define STAI_IDS_WEIGHTS_2_SCALES \
  { \
    0.000984238693490624 \
  }
#define STAI_IDS_WEIGHTS_2_OFFSETS \
  { \
    0 \
  }

#define STAI_IDS_WEIGHTS_3_ALIGNMENT (16)
#define STAI_IDS_WEIGHTS_3_NAME "Gemm_10_weights_transposed_15"
#define STAI_IDS_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_IDS_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_IDS_WEIGHTS_3_SIZE (2048)
#define STAI_IDS_WEIGHTS_3_SIZE_BYTES (2048)
#define STAI_IDS_WEIGHTS_3_CHANNEL (64)
#define STAI_IDS_WEIGHTS_3_HEIGHT (1)
#define STAI_IDS_WEIGHTS_3_WIDTH (1)
#define STAI_IDS_WEIGHTS_3_BATCH (64)
#define STAI_IDS_WEIGHTS_3_RANK (4)
#define STAI_IDS_WEIGHTS_3_SHAPE \
  { \
    32, 1, 1, 64 \
  }
#define STAI_IDS_WEIGHTS_3_SCALE_OFFSET_NUM (1)
#define STAI_IDS_WEIGHTS_3_SCALES \
  { \
    0.000983905396424234 \
  }
#define STAI_IDS_WEIGHTS_3_OFFSETS \
  { \
    0 \
  }

#define STAI_IDS_WEIGHTS_4_ALIGNMENT (32)
#define STAI_IDS_WEIGHTS_4_NAME "Gemm_13_weights_transposed_21"
#define STAI_IDS_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_IDS_WEIGHTS_4_FORMAT (STAI_FORMAT_S8)
#define STAI_IDS_WEIGHTS_4_SIZE (160)
#define STAI_IDS_WEIGHTS_4_SIZE_BYTES (160)
#define STAI_IDS_WEIGHTS_4_CHANNEL (32)
#define STAI_IDS_WEIGHTS_4_HEIGHT (1)
#define STAI_IDS_WEIGHTS_4_WIDTH (1)
#define STAI_IDS_WEIGHTS_4_BATCH (32)
#define STAI_IDS_WEIGHTS_4_RANK (4)
#define STAI_IDS_WEIGHTS_4_SHAPE \
  { \
    5, 1, 1, 32 \
  }
#define STAI_IDS_WEIGHTS_4_SCALE_OFFSET_NUM (1)
#define STAI_IDS_WEIGHTS_4_SCALES \
  { \
    0.00138848018832505 \
  }
#define STAI_IDS_WEIGHTS_4_OFFSETS \
  { \
    0 \
  }

#define STAI_IDS_WEIGHTS_5_ALIGNMENT (32)
#define STAI_IDS_WEIGHTS_5_NAME "Gemm_4_conv_4_off_bias_32"
#define STAI_IDS_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_IDS_WEIGHTS_5_FORMAT (STAI_FORMAT_S32)
#define STAI_IDS_WEIGHTS_5_SIZE (64)
#define STAI_IDS_WEIGHTS_5_SIZE_BYTES (256)
#define STAI_IDS_WEIGHTS_5_CHANNEL (64)
#define STAI_IDS_WEIGHTS_5_HEIGHT (1)
#define STAI_IDS_WEIGHTS_5_WIDTH (1)
#define STAI_IDS_WEIGHTS_5_BATCH (16)
#define STAI_IDS_WEIGHTS_5_RANK (4)
#define STAI_IDS_WEIGHTS_5_SHAPE \
  { \
    4, 1, 1, 16 \
  }
#define STAI_IDS_WEIGHTS_5_SCALE_OFFSET_NUM (0)
#define STAI_IDS_WEIGHTS_5_SCALES \
  { \
  }
#define STAI_IDS_WEIGHTS_5_OFFSETS \
  { \
  }

#define STAI_IDS_WEIGHTS_6_ALIGNMENT (16)
#define STAI_IDS_WEIGHTS_6_NAME "Gemm_7_conv_10_zero_off_35"
#define STAI_IDS_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_IDS_WEIGHTS_6_FORMAT (STAI_FORMAT_S8)
#define STAI_IDS_WEIGHTS_6_SIZE (1)
#define STAI_IDS_WEIGHTS_6_SIZE_BYTES (1)
#define STAI_IDS_WEIGHTS_6_CHANNEL (1)
#define STAI_IDS_WEIGHTS_6_HEIGHT (1)
#define STAI_IDS_WEIGHTS_6_WIDTH (1)
#define STAI_IDS_WEIGHTS_6_RANK (1)
#define STAI_IDS_WEIGHTS_6_SHAPE \
  { \
    1 \
  }
#define STAI_IDS_WEIGHTS_6_SCALE_OFFSET_NUM (1)
#define STAI_IDS_WEIGHTS_6_SCALES \
  { \
    0.00823040958493948 \
  }
#define STAI_IDS_WEIGHTS_6_OFFSETS \
  { \
    0 \
  }

#define STAI_IDS_WEIGHTS_7_ALIGNMENT (32)
#define STAI_IDS_WEIGHTS_7_NAME "Gemm_7_conv_10_off_bias_41"
#define STAI_IDS_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_IDS_WEIGHTS_7_FORMAT (STAI_FORMAT_S32)
#define STAI_IDS_WEIGHTS_7_SIZE (64)
#define STAI_IDS_WEIGHTS_7_SIZE_BYTES (256)
#define STAI_IDS_WEIGHTS_7_CHANNEL (64)
#define STAI_IDS_WEIGHTS_7_HEIGHT (1)
#define STAI_IDS_WEIGHTS_7_WIDTH (1)
#define STAI_IDS_WEIGHTS_7_BATCH (16)
#define STAI_IDS_WEIGHTS_7_RANK (4)
#define STAI_IDS_WEIGHTS_7_SHAPE \
  { \
    4, 1, 1, 16 \
  }
#define STAI_IDS_WEIGHTS_7_SCALE_OFFSET_NUM (0)
#define STAI_IDS_WEIGHTS_7_SCALES \
  { \
  }
#define STAI_IDS_WEIGHTS_7_OFFSETS \
  { \
  }

#define STAI_IDS_WEIGHTS_8_ALIGNMENT (32)
#define STAI_IDS_WEIGHTS_8_NAME "Gemm_10_conv_16_zero_off_44"
#define STAI_IDS_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_IDS_WEIGHTS_8_FORMAT (STAI_FORMAT_S8)
#define STAI_IDS_WEIGHTS_8_SIZE (1)
#define STAI_IDS_WEIGHTS_8_SIZE_BYTES (1)
#define STAI_IDS_WEIGHTS_8_CHANNEL (1)
#define STAI_IDS_WEIGHTS_8_HEIGHT (1)
#define STAI_IDS_WEIGHTS_8_WIDTH (1)
#define STAI_IDS_WEIGHTS_8_RANK (1)
#define STAI_IDS_WEIGHTS_8_SHAPE \
  { \
    1 \
  }
#define STAI_IDS_WEIGHTS_8_SCALE_OFFSET_NUM (1)
#define STAI_IDS_WEIGHTS_8_SCALES \
  { \
    0.00395985832437873 \
  }
#define STAI_IDS_WEIGHTS_8_OFFSETS \
  { \
    0 \
  }

#define STAI_IDS_WEIGHTS_9_ALIGNMENT (16)
#define STAI_IDS_WEIGHTS_9_NAME "Gemm_10_conv_16_off_bias_50"
#define STAI_IDS_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_IDS_WEIGHTS_9_FORMAT (STAI_FORMAT_S32)
#define STAI_IDS_WEIGHTS_9_SIZE (32)
#define STAI_IDS_WEIGHTS_9_SIZE_BYTES (128)
#define STAI_IDS_WEIGHTS_9_CHANNEL (32)
#define STAI_IDS_WEIGHTS_9_HEIGHT (1)
#define STAI_IDS_WEIGHTS_9_WIDTH (1)
#define STAI_IDS_WEIGHTS_9_BATCH (16)
#define STAI_IDS_WEIGHTS_9_RANK (4)
#define STAI_IDS_WEIGHTS_9_SHAPE \
  { \
    2, 1, 1, 16 \
  }
#define STAI_IDS_WEIGHTS_9_SCALE_OFFSET_NUM (0)
#define STAI_IDS_WEIGHTS_9_SCALES \
  { \
  }
#define STAI_IDS_WEIGHTS_9_OFFSETS \
  { \
  }

#define STAI_IDS_WEIGHTS_10_ALIGNMENT (16)
#define STAI_IDS_WEIGHTS_10_NAME "Gemm_13_conv_22_zero_off_53"
#define STAI_IDS_WEIGHTS_10_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_IDS_WEIGHTS_10_FORMAT (STAI_FORMAT_S8)
#define STAI_IDS_WEIGHTS_10_SIZE (1)
#define STAI_IDS_WEIGHTS_10_SIZE_BYTES (1)
#define STAI_IDS_WEIGHTS_10_CHANNEL (1)
#define STAI_IDS_WEIGHTS_10_HEIGHT (1)
#define STAI_IDS_WEIGHTS_10_WIDTH (1)
#define STAI_IDS_WEIGHTS_10_RANK (1)
#define STAI_IDS_WEIGHTS_10_SHAPE \
  { \
    1 \
  }
#define STAI_IDS_WEIGHTS_10_SCALE_OFFSET_NUM (1)
#define STAI_IDS_WEIGHTS_10_SCALES \
  { \
    0.00183256738819182 \
  }
#define STAI_IDS_WEIGHTS_10_OFFSETS \
  { \
    0 \
  }

#define STAI_IDS_WEIGHTS_11_ALIGNMENT (16)
#define STAI_IDS_WEIGHTS_11_NAME "Gemm_13_conv_22_off_bias_59"
#define STAI_IDS_WEIGHTS_11_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_IDS_WEIGHTS_11_FORMAT (STAI_FORMAT_S32)
#define STAI_IDS_WEIGHTS_11_SIZE (5)
#define STAI_IDS_WEIGHTS_11_SIZE_BYTES (20)
#define STAI_IDS_WEIGHTS_11_CHANNEL (5)
#define STAI_IDS_WEIGHTS_11_HEIGHT (1)
#define STAI_IDS_WEIGHTS_11_WIDTH (1)
#define STAI_IDS_WEIGHTS_11_BATCH (5)
#define STAI_IDS_WEIGHTS_11_RANK (3)
#define STAI_IDS_WEIGHTS_11_SHAPE \
  { \
    1, 1, 5 \
  }
#define STAI_IDS_WEIGHTS_11_SCALE_OFFSET_NUM (0)
#define STAI_IDS_WEIGHTS_11_SCALES \
  { \
  }
#define STAI_IDS_WEIGHTS_11_OFFSETS \
  { \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_IDS_WEIGHTS_NUM (0)
#define STAI_IDS_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_IDS_WEIGHTS_NAMES \
  { \
  }
#define STAI_IDS_WEIGHTS_FORMATS \
  { \
  }
#define STAI_IDS_WEIGHTS_SIZES \
  { \
  }
#define STAI_IDS_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_IDS_ACTIVATIONS_NUM (0)
#define STAI_IDS_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_IDS_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_IDS_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_IDS_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_IDS_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_IDS_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_IDS_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_IDS_ORIGIN_MODEL_NAME "can_h64_int8_OE_3_3_1"
#define STAI_IDS_C_MODEL_NAME "ids"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_IDS_H
