"""Build RM01 into a fresh directory, reusing RA01's exact compile recipe.

Every compile command is RA01's recorded argv (results/ra4e1_v5_build_20260925_01/
compile_NN.json) with only: app.c -> rm01.c, wire.c dropped (RA01 host wire
protocol, unused), -I ra4e1_v5 -> -I firmware_measure (identical bsp_cfg.h,
checked), object paths -> the new build dir. One extra unit, rm_vectors.c, is
generated from the pinned validation archive (1024 inputs + QDQ reference
outputs, FP32 words verbatim). Link = RA01's link flags with this linker.ld.
Nothing here touches hardware.

usage: .venv/bin/python build.py --output-dir <fresh absolute dir>
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys

import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
RA01 = REPO / 'results/ra4e1_v5_build_20260925_01'
RA01_APP = REPO / 'tools/board_deployment/ra4e1_v5/app.c'
RA01_WIRE = REPO / 'tools/board_deployment/shared_v5/wire.c'
RA01_INC = REPO / 'tools/board_deployment/ra4e1_v5'
BUNDLE = REPO / 'results/v5_exports_20260922_r6_1_remaining19/nslkdd/qcfs/qdq'
TOOLS = Path('/home/thc1006/opt/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin')
PINS = {
    BUNDLE / 'validation_vectors.npz': 'cb5b3415cdbfb8a27db471f972f73910f7a5503687d79446458b8a48c4ae1edb',
    BUNDLE / 'model_qdq_int8.onnx': '22dc7979340c34af613840a8cef70bc07f469ae2143925660cf3312f36475e2d',
    REPO / 'results/portable_qdq_native_20260925_01/model_sources/model.c':
        'bba723cc7b031815c2aaf848f6893eb87dd91cb05f5580f93df611be489bb1e9',
    RA01 / 'firmware.elf': 'fbe5bdd0f4cf5138d37336a01ba2a5bdf4c1923060db32d9c9c9356c947066fe',
}
RESULT_ADDRESS = 0x2001C000
RESULT_BYTES = 0x2100


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def require(ok, msg):
    if not ok:
        raise SystemExit('BUILD REFUSED: ' + msg)


def vectors_c(npz_path):
    z = np.load(npz_path)
    x = np.ascontiguousarray(z['x'], dtype='<f4')
    ref = np.ascontiguousarray(z['reference_logits'], dtype='<f4')
    require(x.shape == (1024, 41) and ref.shape == (1024, 5), 'vector shapes')
    require(np.isfinite(x).all() and np.isfinite(ref).all(), 'nonfinite vectors')
    xi, ri = x.view('<u4').ravel(), ref.view('<u4').ravel()

    def arr(name, words):
        body = ',\n'.join(', '.join(f'0x{w:08x}u' for w in words[i:i + 8]) for i in range(0, len(words), 8))
        return f'const uint32_t {name}[{len(words)}] = {{\n{body}\n}};\n'
    text = ('/* Generated by build.py from validation_vectors.npz (sha256 '
            f'{PINS[npz_path]}): x and reference_logits, FP32 words verbatim. */\n'
            '#include "rm01.h"\n'
            f'const char rm_vectors_sha256[65] = "{PINS[npz_path]}";\n'
            + arr('rm_inputs', xi) + arr('rm_expected', ri))
    return text, dict(inputs_sha256=hashlib.sha256(xi.tobytes()).hexdigest(),
                      expected_sha256=hashlib.sha256(ri.tobytes()).hexdigest(),
                      row_ids_first=[int(v) for v in z['validation_row_ids'][:4]])


def run(argv, out, name):
    p = subprocess.run(argv, capture_output=True, text=True, timeout=600)
    (out / f'{name}.stdout').write_text(p.stdout)
    (out / f'{name}.stderr').write_text(p.stderr)
    rec = dict(argv=argv, returncode=p.returncode)
    (out / f'{name}.json').write_text(json.dumps(rec, indent=1) + '\n')
    require(p.returncode == 0, f'{name} failed: {p.stderr[-2000:]}')
    return p.stdout


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--output-dir', type=Path, required=True)
    args = ap.parse_args(argv)
    out = args.output_dir
    require(out.is_absolute() and not os.path.lexists(out), 'use a fresh absolute --output-dir')
    for p, want in PINS.items():
        require(sha(p) == want, f'pin mismatch {p}')
    require((HERE / 'bsp_cfg.h').read_bytes() == (RA01_INC / 'bsp_cfg.h').read_bytes(),
            'bsp_cfg.h differs from RA01')
    out.mkdir(parents=True)
    text, vec = vectors_c(BUNDLE / 'validation_vectors.npz')
    (out / 'rm_vectors.c').write_text(text)

    recipe = sorted(RA01.glob('compile_*.json'))
    require(len(recipe) == 28, f'expected 28 RA01 compile records, found {len(recipe)}')
    commands, objs = [], []
    for rec in recipe:
        a = json.loads(rec.read_text())['argv']
        src = Path(a[a.index('-c') + 1])
        if src == RA01_WIRE:
            continue
        if src == RA01_APP:
            src = HERE / 'rm01.c'
        commands.append((a, src))
    commands.append((commands[0][0], out / 'rm_vectors.c'))   # same flags as the app unit
    for k, (a, src) in enumerate(commands):
        a = list(a)
        a[a.index('-c') + 1] = str(src)
        obj = out / f'obj_{k:02d}.o'
        a[a.index('-o') + 1] = str(obj)
        a[a.index('-MF') + 1] = str(out / f'obj_{k:02d}.d')
        i = a.index(str(RA01_INC))
        require(a[i - 1] == '-I', 'include layout')
        a[i] = str(HERE)
        run(a, out, f'compile_{k:02d}')
        objs.append(str(obj))

    link = json.loads((RA01 / 'link.json').read_text())['argv']
    first = next(i for i, x in enumerate(link) if x.endswith('.o'))
    last = max(i for i, x in enumerate(link) if x.endswith('.o'))
    link = link[:first] + objs + link[last + 1:]
    link[link.index('-T') + 1] = str(HERE / 'linker.ld')
    link = [f'-Wl,-Map={out / "firmware.map"}' if x.startswith('-Wl,-Map=') else x for x in link]
    link[link.index('-o') + 1] = str(out / 'firmware.elf')
    run(link, out, 'link')
    elf = out / 'firmware.elf'
    run([str(TOOLS / 'arm-none-eabi-objcopy'), '-O', 'binary', str(elf), str(out / 'firmware.bin')], out, 'binary')
    run([str(TOOLS / 'arm-none-eabi-objcopy'), '-O', 'ihex', str(elf), str(out / 'firmware.hex')], out, 'hex')
    size = run([str(TOOLS / 'arm-none-eabi-size'), '-A', str(elf)], out, 'size')
    nm = run([str(TOOLS / 'arm-none-eabi-nm'), '-S', '-n', str(elf)], out, 'symbols')
    run([str(TOOLS / 'arm-none-eabi-objdump'), '-d', str(elf)], out, 'disassembly')
    sections = run([str(TOOLS / 'arm-none-eabi-objdump'), '-h', str(elf)], out, 'sections')
    run([str(TOOLS / 'arm-none-eabi-gcc'), '--version'], out, 'compiler_version')

    deps = set()
    for dfile in sorted(out.glob('obj_*.d')):
        body = dfile.read_text().replace('\\\n', ' ')
        for tok in body.split(':', 1)[1].split():
            deps.add(str(Path(tok).resolve()))
    deps.update(str(Path(x).resolve()) for x in (HERE / 'linker.ld',
                '/home/thc1006/dev/SpikeIDS-RA4E1/firmware/ra4e1_skeleton/memory_regions.ld',
                '/home/thc1006/dev/SpikeIDS-RA4E1/firmware/ra4e1_skeleton/fsp_gen.ld'))
    dependency_sha256 = {d: sha(d) for d in sorted(deps)}
    ra01_cc = (RA01 / 'compiler_version.stdout').read_text()
    this_cc = (out / 'compiler_version.stdout').read_text()
    require(ra01_cc == this_cc, 'compiler version differs from RA01')
    syms = {}
    for line in nm.splitlines():
        f = line.split()
        if len(f) == 4:
            syms[f[3]] = (int(f[0], 16), int(f[1], 16))
    require(syms.get('g_rm') == (RESULT_ADDRESS, RESULT_BYTES), f"g_rm placement {syms.get('g_rm')}")
    require(syms['rm_inputs'][1] == 1024 * 41 * 4 and syms['rm_expected'][1] == 1024 * 5 * 4, 'vector sizes')
    require('option_setting' not in sections, 'option-setting section present in image')
    bin_bytes = (out / 'firmware.bin').stat().st_size
    require(bin_bytes < 0x80000, 'image exceeds 512 KiB code flash')
    result = dict(
        schema='rm01-build-v1', firmware='RM01', board='FPB-RA4E1 (R7FA4E10D2CFM)',
        marker='P107 = J5-5 (Arduino D4)', result_block=hex(RESULT_ADDRESS),
        recipe='RA01 compile/link argv verbatim except app.c->rm01.c, wire.c dropped, include dir, linker.ld',
        ra01_recipe_dir=str(RA01), pins={str(k): v for k, v in PINS.items()},
        sources_sha256={str(p): sha(p) for p in [HERE / 'rm01.c', HERE / 'rm01.h', HERE / 'linker.ld',
                                                 HERE / 'bsp_cfg.h', Path(__file__).resolve()]},
        portable_sources_sha256={str(p): sha(p) for _, p in commands if 'portable_qdq' in str(p) or 'model.c' in str(p)},
        vectors=vec, bin_bytes=bin_bytes,
        sha256={n: sha(out / n) for n in ('firmware.elf', 'firmware.bin', 'firmware.hex', 'rm_vectors.c')},
        symbols={k: [hex(v[0]), v[1]] for k, v in syms.items()
                 if k in ('g_rm', 'rm_inputs', 'rm_expected', 'spikeids_qdq_model', 'hal_entry', 'g_main_stack')},
        size_A=size, hardware_accessed=False, compiler_version_equals_ra01=True,
        dependency_count=len(dependency_sha256), dependency_sha256=dependency_sha256)
    (out / 'RESULT.json').write_text(json.dumps(result, indent=1) + '\n')
    print(json.dumps(dict(ok=True, out=str(out), bin_bytes=bin_bytes, **result['sha256']), indent=1))
    return 0


if __name__ == '__main__':
    sys.exit(main())
