"""Derive em01.c (ESP32-S3) from the frozen RM01 source (FPB-RA4E1, build_03).

Every substitution is platform plumbing and must apply exactly once; the whole
measurement logic (parity, wiring/sham pulses, calibration, schedules, window
bookkeeping, telemetry) stays byte-identical. test_em01.py re-runs this and
requires em01.c == derive(rm01.c).

usage: python derive_em01.py [--check]
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RM01 = HERE.parents[1] / 'ra4e1_deployment/firmware_measure/rm01.c'
OUT = HERE / 'em01.c'

HEADER = '''/* EM01: ESP32-S3 port of RM01, GENERATED by derive_em01.py from
 * tools/ra4e1_deployment/firmware_measure/rm01.c -- do not edit by hand.
 *
 * Same model path (portable_qdq.c + model.c, strict FP32 flags), same autonomous
 * sequence, window kinds, checksums and telemetry encoding as RM01, so the same
 * decoder/analysis applies. Platform differences only: marker = EM_MARKER_GPIO
 * (em01.h; GPIO5 since ESP Amendment 1), one non-inlined IRAM busy-wait for every
 * wait (EM_WAIT_ATTR, ESP Amendment 2),
 * time base = Xtensa CCOUNT at the CPU clock (240 MHz from the 40 MHz crystal),
 * snapshot words 0xD0.. = APB/XTAL/CPU clock, reset reason, tick rate, core,
 * flash size, IDF version. Entry hal_entry() is called by app_main.c. */'''

def derive(src):
    head_end = src.index('*/') + 2
    out = HEADER + src[head_end:]
    subs = [
        ('#include "hal_data.h"\n#include "portable_qdq.h"\n#include "rm01.h"\n',
         '#include "portable_qdq.h"\n#include "em01.h"\n#include "em01_port.h"\n'),
        ('volatile rm_result_t g_rm __attribute__((section(".rm01_result"), aligned(32), used));',
         'volatile rm_result_t g_rm __attribute__((aligned(32), used));'),
        ('/* Generated FSP vectors keep the CAN ISR slot; CAN is never opened here. */\n'
         'void can_callback(can_callback_args_t *args) { (void)args; }\n\n', ''),
        ('    return R_GPT1->GTCNT;\n', '    return em_cycles();\n'),
        ('    R_PORT1->PCNTR3 = high ? (UINT32_C(1) << 7) : (UINT32_C(1) << (7 + 16));\n',
         '    em_marker_write(high);\n'),
        ('    R_BSP_PinAccessEnable();\n'
         '    R_BSP_PinCfg(BSP_IO_PORT_01_PIN_07, BSP_IO_PFS_PDR_OUTPUT);   /* output, PODR=0 (LOW) */\n'
         '    R_BSP_PinAccessDisable();\n',
         '    em_marker_setup();                     /* push-pull output, no pulls, LOW */\n'),
        ('    g_rm.fcachee = R_FCACHE->FCACHEE;\n'
         '    g_rm.flwt = R_FCACHE->FLWT;\n'
         '    g_rm.sckdivcr = R_SYSTEM->SCKDIVCR; g_rm.sckscr = R_SYSTEM->SCKSCR;\n'
         '    g_rm.pllccr = R_SYSTEM->PLLCCR; g_rm.pllcr = R_SYSTEM->PLLCR;\n'
         '    g_rm.hococr = R_SYSTEM->HOCOCR; g_rm.mococr = R_SYSTEM->MOCOCR; g_rm.opccr = R_SYSTEM->OPCCR;\n'
         '    g_rm.ofs1_sec = *RM_OFS1_SEC_PTR;        /* option setting OFS1_SEC: HOCOFRQ lives here */\n'
         '    g_rm.cpuid = SCB->CPUID;\n',
         '    em_snapshot(&g_rm);                      /* clocks, reset reason, chip, flash, IDF */\n'),
        ('    R_BSP_MODULE_START(FSP_IP_GPT, 1);\n'
         '    R_GPT1->GTCR = 0;                        /* stopped, saw-wave mode, PCLKD/1 */\n'
         '    R_GPT1->GTUDDTYC = 1;                    /* count up */\n'
         '    R_GPT1->GTPR = UINT32_C(0xFFFFFFFF);     /* full 32-bit period: natural wrap */\n'
         '    R_GPT1->GTCNT = 0;\n'
         '    R_GPT1->GTCR = 1;                        /* CST: start */\n'
         '    __DSB();\n'
         '    g_rm.timer_ctrl = R_GPT1->GTCR;\n',
         '    g_rm.timer_ctrl = 1u;                    /* CCOUNT: always running, 32-bit wrap */\n'),
        ('    if (cycles_now() == c0 || R_GPT1->GTPR != UINT32_C(0xFFFFFFFF)) ok = fail(RM_E_TIMER, g_rm.timer_ctrl);\n',
         '    if (cycles_now() == c0) ok = fail(RM_E_TIMER, g_rm.timer_ctrl);\n'),
        ('    for (;;) __NOP();              /* no WFI: keep the core debuggable for readback */\n',
         '    for (;;) __NOP();              /* spin: no sleep, same state as RM01 DONE */\n'),
        # ESP Amendment 2 (review B1): every wait runs ONE copy of the busy-wait. Inlined
        # copies sat at different addresses/cache-line alignments and drew different
        # currents, which made the sham's HIGH and LOW halves run different code.
        ('static void wait_cycles(uint32_t cycles)\n',
         'static void EM_WAIT_ATTR wait_cycles(uint32_t cycles)\n'),
    ]
    for old, new in subs:
        n = out.count(old)
        if n != 1:
            raise SystemExit(f'derive_em01: substitution applies {n} times (must be 1): {old[:60]!r}')
        out = out.replace(old, new)
    return out


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    text = derive(RM01.read_text())
    if '--check' in argv:
        ok = OUT.exists() and OUT.read_text() == text
        print('em01.c matches derive(rm01.c)' if ok else 'em01.c DIFFERS from derive(rm01.c)')
        return 0 if ok else 1
    OUT.write_text(text)
    print(f'wrote {OUT}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
