"""Emit LaTeX \newcommand macros from 20-seed + CNN + CICIDS result JSONs.

Usage:
    python scripts/emit_paper_macros.py \
        --nslkdd results/multiseed_20seed.json \
        --unsw   results/unsw_20seed.json \
        --cicids results/cicids2017_multiseed_experiment.json \
        --cnn    results/cnn_baseline.json \
        --stats  results/stats_report.json \
        --out    paper/globecom/result_macros.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _fmt(mean: float, std: float, pct: bool = True) -> str:
    if pct:
        return f"{mean:.2f}$\\pm${std:.2f}"
    return f"{mean:.4f}$\\pm${std:.4f}"


def _mean_std(rel_json: dict, metric: str) -> tuple[float, float] | None:
    """Pull mean/std from a per_seed list with {overall_acc, macro_f1, ...}.

    Accepts either {"relu": {"per_seed": [...]}} or {"per_seed": [...]}.
    Values in per_seed are percentages (0-100), not fractions.
    """
    if "per_seed" not in rel_json and "relu" in rel_json:
        rel_json = rel_json["relu"]
    per_seed = rel_json.get("per_seed")
    if not per_seed:
        return None
    vals = [float(r[metric]) for r in per_seed if metric in r]
    if not vals:
        return None
    import statistics
    m = statistics.mean(vals)
    s = statistics.stdev(vals) if len(vals) > 1 else 0.0
    return m, s


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--nslkdd", type=Path, required=False)
    ap.add_argument("--unsw", type=Path, required=False)
    ap.add_argument("--cicids", type=Path, required=False)
    ap.add_argument("--cnn", type=Path, required=False)
    ap.add_argument("--unsw-qcfs", type=Path, required=False,
                     dest="unsw_qcfs",
                     help="results/unsw_qcfs_multiseed.json")
    ap.add_argument("--cicids-qcfs", type=Path, required=False,
                     dest="cicids_qcfs",
                     help="results/cicids_qcfs_multiseed.json")
    ap.add_argument("--stats", type=Path, required=False)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    lines: list[str] = [
        "% Auto-generated by scripts/emit_paper_macros.py",
        "% DO NOT EDIT BY HAND — rerun the script after new experiments.",
        "",
    ]

    def emit(cmd: str, value: str) -> None:
        lines.append(f"\\renewcommand{{\\{cmd}}}{{{value}}}")

    # ── NSL-KDD 20-seed (ReLU + QCFS) ──────────────────────────────────
    if args.nslkdd and args.nslkdd.exists():
        data = json.loads(args.nslkdd.read_text())
        relu = data["relu"]
        qcfs = data.get("qcfs_L4", {})
        ms = _mean_std(relu, "overall_acc")
        if ms:
            emit("nsloarelu", _fmt(*ms))
        ms = _mean_std(relu, "macro_f1")
        if ms:
            emit("nslmfrelu", _fmt(*ms))
        if qcfs:
            ms = _mean_std(qcfs, "overall_acc")
            if ms:
                emit("nsloaqcfs", _fmt(*ms))
            ms = _mean_std(qcfs, "macro_f1")
            if ms:
                emit("nslmfqcfs", _fmt(*ms))

    # ── UNSW-NB15 20-seed (ReLU) ───────────────────────────────────────
    if args.unsw and args.unsw.exists():
        data = json.loads(args.unsw.read_text())
        relu = data.get("relu") or data  # flat schema support
        ms = _mean_std(relu, "overall_acc")
        if ms:
            emit("unswoarelu", _fmt(*ms))
        ms = _mean_std(relu, "macro_f1")
        if ms:
            emit("unswmfrelu", _fmt(*ms))

    # ── CICIDS2017 ─────────────────────────────────────────────────────
    if args.cicids and args.cicids.exists():
        data = json.loads(args.cicids.read_text())
        relu = data.get("relu") or data
        ms = _mean_std(relu, "overall_acc")
        if ms:
            emit("cicoarelu", _fmt(*ms))
        ms = _mean_std(relu, "macro_f1")
        if ms:
            emit("cicmfrelu", _fmt(*ms))

    # ── UNSW-NB15 QCFS (new) ───────────────────────────────────────────
    if args.unsw_qcfs and args.unsw_qcfs.exists():
        data = json.loads(args.unsw_qcfs.read_text())
        qcfs = data.get("qcfs") or data
        ms = _mean_std(qcfs, "overall_acc")
        if ms:
            emit("unswoaqcfs", _fmt(*ms))
        ms = _mean_std(qcfs, "macro_f1")
        if ms:
            emit("unswmfqcfs", _fmt(*ms))

    # ── CICIDS2017 QCFS (new) ──────────────────────────────────────────
    if args.cicids_qcfs and args.cicids_qcfs.exists():
        data = json.loads(args.cicids_qcfs.read_text())
        qcfs = data.get("qcfs") or data
        ms = _mean_std(qcfs, "overall_acc")
        if ms:
            emit("cicoaqcfs", _fmt(*ms))
        ms = _mean_std(qcfs, "macro_f1")
        if ms:
            emit("cicmfqcfs", _fmt(*ms))

    # ── TinyCNN baseline (NSL-KDD, UNSW, optional CICIDS) ──────────────
    if args.cnn and args.cnn.exists():
        data = json.loads(args.cnn.read_text())
        mapping = {
            "nslkdd": ("nsloacnn", "nslmfcnn"),
            "unsw": ("unswoacnn", "unswmfcnn"),
            "cicids2017": ("cicoacnn", "cicmfcnn"),
        }
        for ds, (oa_cmd, mf_cmd) in mapping.items():
            block = data.get(ds)
            if not block:
                continue
            agg = block.get("aggregate", {})
            oa = agg.get("overall_acc", {})
            mf = agg.get("macro_f1", {})
            if oa and "mean" in oa:
                emit(oa_cmd, f"{oa['mean']:.2f}$\\pm${oa.get('std', 0.0):.2f}")
            if mf and "mean" in mf:
                emit(mf_cmd, f"{mf['mean']:.2f}$\\pm${mf.get('std', 0.0):.2f}")

    # ── Statistical test results ──────────────────────────────────────
    if args.stats and args.stats.exists():
        stats = json.loads(args.stats.read_text())
        datasets = stats.get("datasets", {})

        def _fmt_p(p):
            if p is None:
                return "--"
            return f"{p:.3f}"

        def _fmt_dz(dz):
            if dz is None:
                return "--"
            sign = "+" if dz >= 0 else ""
            return f"${sign}{dz:.2f}$"

        def _reject_mark(p_adj):
            if p_adj is None:
                return r"\ding{55}"
            return r"\checkmark" if p_adj <= 0.05 else r"\ding{55}"

        unsw_cmp = datasets.get("unsw", {}).get("comparisons", {})
        unsw_qcfs = unsw_cmp.get("unsw_relu_vs_qcfs")
        if unsw_qcfs:
            emit("unswpqcfs", _fmt_p(unsw_qcfs.get("p_raw", unsw_qcfs.get("p"))))
            emit("unswpadjqcfs", _fmt_p(unsw_qcfs.get("p_adj")))
            emit("unswdzqcfs", _fmt_dz(unsw_qcfs.get("dz")))
            emit("unswrejqcfs", _reject_mark(unsw_qcfs.get("p_adj")))

        cic_cmp = datasets.get("cicids2017", {}).get("comparisons", {})
        cic_qcfs = cic_cmp.get("cicids_relu_vs_qcfs")
        if cic_qcfs:
            emit("cicpqcfs", _fmt_p(cic_qcfs.get("p_raw", cic_qcfs.get("p"))))
            emit("cicpadjqcfs", _fmt_p(cic_qcfs.get("p_adj")))
            emit("cicdzqcfs", _fmt_dz(cic_qcfs.get("dz")))
            emit("cicrejqcfs", _reject_mark(cic_qcfs.get("p_adj")))

        # Also emit \punswrelu and \pcicrelu so prose can inline them
        if unsw_qcfs:
            emit("punswrelu", _fmt_p(unsw_qcfs.get("p_raw", unsw_qcfs.get("p"))))
        if cic_qcfs:
            emit("pcicrelu", _fmt_p(cic_qcfs.get("p_raw", cic_qcfs.get("p"))))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(lines)} lines to {args.out}")


if __name__ == "__main__":
    main()
