#!/usr/bin/env python3
"""Path B on-target NPU-latency measurement for the STM32N6570-DK (self-contained loader).

The ST-official target-validation flow (scripts/N6_reloc/st_load_and_run.py) needs the
ST-LINK GDB server, which ships only inside STM32CubeIDE/CubeCLT. This driver keeps every
ST-official *measurement* component (the delivered validation firmware, the relocatable
model, and the stm_ai_runner serial protocol) and only replaces the firmware *loader*:

  1. CubeProgrammer + MX66 external loader flash  header (MREL) -> 0x70FFF000
                                                   model  bin  -> 0x71000000
  2. pyOCD loads the ST validation firmware (an SRAM image) and starts it   [replaces gdbserver]
  3. stm_ai_runner talks the AI-validation protocol over the ST-Link VCP    [ST-official]
     and reports on-board NPU inference latency (per-layer + total).

Board prereq: BOOT1 = DEV (SW1 pos 1-3). DEV mode keeps the debug AP alive (BootROM waits)
and the validation firmware self-initialises xSPI2 memory-mapping, so the NPU reads the model
at 0x71000000 without depending on the OOB / NORMAL boot (which wedged the debug AP).
"""
from __future__ import annotations
import argparse, subprocess, sys, time, json, statistics, os
from datetime import datetime, timezone
from pathlib import Path

# ST's ai_runner ships protobuf stubs generated by an old protoc: force the pure-Python
# protobuf runtime so they load under a modern protobuf package.
os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

# ST's pb_mgr_drv uses np.fromstring(bytes) (binary mode), removed in modern numpy.
# Route the binary form to np.frombuffer without touching the ST installation.
import numpy as _np
if not getattr(_np, "_fromstring_patched", False):
    _orig_fromstring = getattr(_np, "fromstring", None)
    def _fromstring_compat(string, dtype=float, count=-1, sep=""):
        if sep == "":
            return _np.frombuffer(string, dtype=dtype, count=count)
        return _orig_fromstring(string, dtype=dtype, count=count, sep=sep)
    _np.fromstring = _fromstring_compat
    _np._fromstring_patched = True

ROOT = Path(__file__).resolve().parent.parent
STEDGEAI = Path("/home/thc1006/opt/stedgeai/3.0")
N6RELOC = STEDGEAI / "scripts" / "N6_reloc"
AIRUNNER = STEDGEAI / "scripts" / "ai_runner"
VALID_ELF = N6RELOC / "test" / "stm32n6570-dk-validation-reloc.elf"
CP = Path("/home/thc1006/opt/STMicroelectronics/STM32CubeProgrammer/bin/STM32_Programmer_CLI")
EXTLOADER = CP.parent / "ExternalLoader" / "MX66UW1G45G_STM32N6570-DK.stldr"

HEADER_ADDR = 0x70FFF000
MODEL_ADDR = 0x71000000
FW_ENTRY = 0x3401E7BC  # Reset_Handler of the validation firmware


def flash(header_bin: Path, model_bin: Path, verbosity: int = 0):
    """Flash MREL header + relocatable model to xSPI2 via CubeProgrammer + external loader."""
    assert CP.is_file(), f"CubeProgrammer not found: {CP}"
    assert EXTLOADER.is_file(), f"external loader not found: {EXTLOADER}"
    # ST st_load_and_run does a powerdown-reset first: a freely-running / leftover-firmware core
    # makes the subsequent hotplug flash fail with 'Unable to get core ID' on AP1. Clear it.
    print("[flash] powerdown-reset to clear the running core ...", flush=True)
    subprocess.run([str(CP), "-q", "-c", "port=SWD", "mode=powerdown", "freq=2000", "ap=1"],
                   capture_output=True, text=True)
    time.sleep(1.0)
    cmd = [str(CP), "-c", "port=SWD", "mode=HOTPLUG", "ap=1", "-el", str(EXTLOADER),
           "--download", str(header_bin), f"0x{HEADER_ADDR:08X}",
           "--download", str(model_bin), f"0x{MODEL_ADDR:08X}", "--verify"]
    print(f"[flash] header -> 0x{HEADER_ADDR:08X}, model -> 0x{MODEL_ADDR:08X}", flush=True)
    r = subprocess.run(cmd, capture_output=True, text=True)
    if verbosity or r.returncode != 0:
        print(r.stdout[-3000:]); print(r.stderr[-1500:], file=sys.stderr)
    if r.returncode != 0:
        raise SystemExit(f"[flash] CubeProgrammer failed (rc={r.returncode})")
    print("[flash] OK (verified)", flush=True)


def load_and_start_fw(elf: Path, wait: float = 40.0, verbosity: int = 0):
    """Load the ST validation firmware (SRAM image) via pyOCD and start it — replaces gdbserver.
    Mimics ST's GDB step (monitor reset; load; set $pc=Reset_Handler) with an added MSPLIM clear
    (the inherited BootROM stack limit would STKOF the firmware prologue on this part)."""
    from pyocd.core.helpers import ConnectHelper
    from elftools.elf.elffile import ELFFile
    t0 = time.time(); sess = None
    while True:
        try:
            sess = ConnectHelper.session_with_chosen_probe(
                target_override="stm32n657x0hxq",
                options={"connect_mode": "halt", "frequency": 4_000_000,
                         "resume_on_disconnect": True})
            if sess is None:
                raise RuntimeError("no probe")
            sess.open(); break
        except Exception as e:
            if time.time() - t0 > wait:
                raise
            try: sess and sess.close()
            except Exception: pass
            print(f"  waiting for probe: {type(e).__name__}", flush=True); time.sleep(0.5)
    t = sess.board.target
    # clean reset+halt so the firmware starts from a known state (ST does `monitor reset`)
    try: t.reset_and_halt()
    except Exception: t.halt()
    cpuid = t.read32(0xE000ED00)
    assert (cpuid & 0xFFF0) == 0xD220, f"unexpected CPUID {cpuid:#x} (want Cortex-M55 0xD22x)"
    loaded = 0; sp0 = None
    with open(elf, "rb") as f:
        e = ELFFile(f)
        for seg in e.iter_segments():
            if seg["p_type"] != "PT_LOAD" or seg["p_filesz"] == 0:
                continue
            d = seg.data(); addr = seg["p_paddr"]
            t.write_memory_block8(addr, d)
            back = bytes(t.read_memory_block8(addr, len(d)))
            assert back == d, f"verify failed @ 0x{addr:08X}"
            if sp0 is None and addr == 0x34000000:
                sp0 = int.from_bytes(d[0:4], "little")  # vector[0] = initial MSP
            loaded += len(d)
    # registers: SP from the firmware's own vector table, PC = Reset_Handler
    if sp0:
        for r in ("msp", "sp"):
            try: t.write_core_register(r, sp0)
            except Exception: pass
    t.write_core_register("xpsr", 0x01000000)  # Thumb
    t.write_core_register("pc", FW_ENTRY & ~1)
    for rn in ("msplim", "psplim"):            # clear inherited stack limit -> no STKOF
        try: t.write_core_register(rn, 0)
        except Exception: pass
    t.resume()
    print(f"[fw] loaded {loaded}B, started at 0x{FW_ENTRY:08X} (SP=0x{sp0:08X})"
          if sp0 else f"[fw] loaded {loaded}B, started at 0x{FW_ENTRY:08X}", flush=True)
    return sess


def measure(desc: str, batch: int, mode_per_layer: bool, out: Path | None):
    """Connect to the running validation firmware over the ST-Link VCP and profile the NPU."""
    sys.path.insert(0, str(AIRUNNER))
    from stm_ai_runner import AiRunner
    runner = AiRunner()
    print(f"[ai] connecting {desc} ...", flush=True)
    runner.connect(desc=desc)
    if not runner.is_connected:
        raise SystemExit(f"[ai] connect failed: {runner.get_error()}")
    names = runner.names
    print(f"[ai] connected. models={names}", flush=True)
    try: runner.summary(print_fn=print)
    except Exception as ex: print(f"[ai] summary skipped: {ex}", flush=True)
    name = names[0]
    inputs = runner.generate_rnd_inputs(name=name, batch_size=batch)
    mode = AiRunner.Mode.PER_LAYER if mode_per_layer else AiRunner.Mode.IO_ONLY
    outputs, profiler = runner.invoke(inputs, mode=mode, name=name)
    runner.print_profiling(inputs, profiler, outputs, print_fn=print)
    # extract per-inference durations (ms) from the profiler
    dur = profiler.get("debug", {}).get("exec_times") if isinstance(profiler, dict) else None
    result = {"timestamp": datetime.now(timezone.utc).isoformat(), "model": name,
              "batch": batch, "desc": desc}
    try:
        c_dur = profiler.get("c_durations") if isinstance(profiler, dict) else None
        if c_dur:
            result["c_durations_ms"] = list(map(float, c_dur))
            result["median_ms"] = statistics.median(result["c_durations_ms"])
            result["min_ms"] = min(result["c_durations_ms"])
            result["max_ms"] = max(result["c_durations_ms"])
    except Exception as ex:
        result["extract_warning"] = str(ex)
    try:
        result["profiler_keys"] = sorted(profiler.keys()) if isinstance(profiler, dict) else None
    except Exception: pass
    runner.disconnect()
    if out:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(result, indent=1))
        print(f"[ai] wrote {out}", flush=True)
    if "median_ms" in result:
        print(f"=== on-board NPU inference: median {result['median_ms']*1000:.3f} us "
              f"(min {result['min_ms']*1000:.3f} / max {result['max_ms']*1000:.3f}) ===", flush=True)
    return result


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build-dir", default=str(ROOT / "firmware/n6b/pathB"),
                    help="dir holding network_rel.bin + header_copy.bin")
    ap.add_argument("--elf", default=str(VALID_ELF))
    ap.add_argument("--port", default="/dev/ttyACM0")
    ap.add_argument("--baud", type=int, default=921600)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--boot-wait", type=float, default=3.0, help="s to wait after fw start")
    ap.add_argument("--probe-wait", type=float, default=40.0)
    ap.add_argument("--skip-flash", action="store_true")
    ap.add_argument("--flash-only", action="store_true")
    ap.add_argument("--io-only", action="store_true", help="IO-only (no per-layer) profiling")
    ap.add_argument("-v", "--verbose", action="count", default=0)
    ap.add_argument("--out", default=None)
    a = ap.parse_args()

    bd = Path(a.build_dir)
    header_bin = bd / "header_copy.bin"; model_bin = bd / "network_rel.bin"
    if not a.skip_flash:
        assert header_bin.is_file(), f"missing {header_bin}"
        assert model_bin.is_file(), f"missing {model_bin}"
        flash(header_bin, model_bin, verbosity=a.verbose)
    if a.flash_only:
        return
    sess = load_and_start_fw(Path(a.elf), wait=a.probe_wait, verbosity=a.verbose)
    try:
        time.sleep(a.boot_wait)
        desc = f"serial:{a.port}:{a.baud}"
        out = Path(a.out) if a.out else ROOT / "results" / f"n6_npu_pathB_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        measure(desc, a.batch, not a.io_only, out)
    finally:
        try: sess.close()
        except Exception: pass


if __name__ == "__main__":
    main()
